# Base URL of site
baseurl = "https://www.mavjs.org/"

# Title of site
title = "Maverick Kaung"

# Copyright notice
copyright = "&copy; 2018 Ye Myat \"Maverick\" Kaung"

# Theme name
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10
defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false

enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# Enable comments by entering your Disqus shortname
#disqusShortname = "spf13"

# Enable analytics by entering your Google Analytics tracking ID
#googleAnalytics = ""

[blackfriday]
  hrefTargetBlank = true
  fractions = true
  smartypants = true

[params]
  # Color Theme
  color_theme = "default"
  
  # Font Style
  font = "default"

  name = "Maverick Kaung"
  role = "Security Enthusiast"
  avatar = "portrait.jpg"
  email = "mavjs01@gmail.com"

  keybase = "mavjs"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"
  time_format = "15:04"

  reading_time = true

  comment_count = false

  section_pager = false

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = false

  # highlight options
  highlight = true
  highlight_languages = []

  # Enable native social sharing buttons?
  sharing = true

  privacy_pack = false
  
  # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
#  [params.posts]
#    count = 5
#    title = "Recent Posts"
#    subtitle = ""
#    str_all = "More Posts"
#    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
  list_children = true
  publication_format = 0

  # Contact section.
#  [params.contact]
#    enable = true
#    title = "Contact"
#    subtitle = ""
#    autolink = true  # Automatically link email and phone?
#    # autolink = false

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
  #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/mavjs"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/MavJS"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/mavjs"

  # disclaimer
  [params.disclaimer]
    enable = true
    title = "Disclaimer"

# Navigation Links
#   The weight parameter defines the order that the links will appear in.
[params.menus]
align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 5

[[menu.main]]
  name = "Disclaimer"
  url = "#disclaimer"
  weight = 6

[taxonomies]
 tag = "tags"
 category = "categories"
 publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[Languages.en]
  languageCode = "en-us"
